--公告信息表
CREATE TABLE T_BULLETIN_TICKET_INFO
(
    I_BULLETIN_SEG_ID  NUMBER(15,0) 	NOT NULL,
    I_IS_SUP           NUMBER(7,0)  	DEFAULT 2       NOT NULL,
    I_TICKET_STATUS    NUMBER(7,0)  	DEFAULT 1       NOT NULL,
    I_BULLETIN_STATUS  NUMBER(7,0)  	NULL,
    I_KIND             NUMBER(7,0)  	NULL,
    I_RELATE_ID        NUMBER(15,0) 	NULL,
    S_RELATE_URL       VARCHAR2(128)  NULL,
    S_CONTENT          VARCHAR2(4000) NOT NULL,
    I_RANGE            NUMBER(7,0)  	NOT NULL,
    S_TITLE            VARCHAR2(128)  NOT NULL,
    S_CODE             VARCHAR2(128)  NOT NULL,
    I_LEVEL            NUMBER(7,0)  	NULL,
    D_BEGIN_DATE       DATE          	NULL,
    D_END_DATE         DATE          	NOT NULL,
    I_NEED_FEEDBACK    NUMBER(7,0)  	DEFAULT 1       NULL,
    I_APPOINT_DOMAIN   NUMBER(7,0)  	DEFAULT 2       NULL,
    I_AUDIT_STAFF_ID   NUMBER(15,0) 	NULL,
    S_AUDIT_STAFF_NAME VARCHAR2(64)   NULL,
    I_DOMAIN_ID        NUMBER(15,0) 	NOT NULL,
    S_DOMAIN_NAME      VARCHAR2(128)  NULL,
    I_DEPT_ID          NUMBER(15,0) 	NULL,
    S_DEPT_NAME        VARCHAR2(128)  NULL,
    I_STAFF_ID         NUMBER(15,0) 	NULL,
    S_STAFF_NAME       VARCHAR2(128)  NULL,
    S_STAFF_TEL        VARCHAR2(30)   NULL,
    D_CREATE_DATE      DATE         	DEFAULT sysdate NULL,
    D_PIGEONHOLE_DATE  DATE          	NULL,
    S_REMARK           VARCHAR2(512)  NULL,
    I_ISSEND_OSS       NUMBER(1,0)  	DEFAULT 0       NULL,
    I_FLAG_OSS         NUMBER(1,0)  	DEFAULT 0       NULL,
    S_STAFF_ACCOUNT    VARCHAR2(32)   NULL
);
alter table T_BULLETIN_TICKET_INFO add constraint PK_IBULLETINSEGID primary key (I_BULLETIN_SEG_ID);

--公告审核表
CREATE TABLE T_PRO_BULLETIN_AUDIT
(
    I_AUDIT_SEG_ID    NUMBER(15,0) 	NOT NULL,
    I_BULLETIN_SEG_ID NUMBER(15,0) 	NOT NULL,
    I_IS_MIND         NUMBER(7,0)  	NOT NULL,
    S_STAFF_NAME      VARCHAR2(128) NOT NULL,
    I_STAFF_ID        NUMBER(15,0) 	NOT NULL,
    S_DEPT_NAME       VARCHAR2(128) NOT NULL,
    I_DEPT_ID         NUMBER(15,0) 	NOT NULL,
    S_DOMAN_NAME      VARCHAR2(128) NOT NULL,
    I_DOMAN_ID        NUMBER(15,0) 	NOT NULL,
    S_STAFF_TEL       VARCHAR2(30)  NOT NULL,
    D_CREATE_DATE     DATE      		NOT NULL,
    I_WFINST_ID       NUMBER(15,0) 	NOT NULL,
    I_ACTINST_ID      NUMBER(15,0) 	NOT NULL,
    I_WORKITEM_ID     NUMBER(15,0) 	NOT NULL,
    S_REMARK          VARCHAR2(255) NOT NULL
);
alter table T_PRO_BULLETIN_AUDIT add constraint PK_IAUDITSEGID primary key (I_AUDIT_SEG_ID);

--公告范围表
CREATE TABLE T_PRO_BULLETIN_RANGE
(
    I_RANGE_SEG_ID    NUMBER(15,0)   NOT NULL,
    I_BULLETIN_SEG_ID NUMBER(15,0)   NULL,
    I_RENGE_TYPE      NUMBER(7,0)    NULL,
    I_OBJ_ID          NUMBER(15,0)   NULL,
    S_OBJ_NAME        VARCHAR2(64)   NULL,
    I_IS_TEMP_DATA    NUMBER(7,0)    NULL,
    I_DOMAIN_ID       NUMBER(15,0)   NULL,
    S_DOMAIN_NAME     VARCHAR2(64)   NULL,
    I_RANGE_MARK      NUMBER(7,0)    NULL,
    S_REMARK          VARCHAR2(512)  NULL
);
alter table T_PRO_BULLETIN_RANGE add constraint PK_IRANGESEGID primary key (I_RANGE_SEG_ID);

/*索引*/
CREATE INDEX idx_iBulletinStatus ON T_BULLETIN_TICKET_INFO (I_BULLETIN_STATUS);
CREATE INDEX idx_iKind ON T_BULLETIN_TICKET_INFO (I_KIND);
CREATE INDEX idx_iRange ON T_BULLETIN_TICKET_INFO (I_RANGE);
CREATE INDEX idx_iLevel ON T_BULLETIN_TICKET_INFO (I_LEVEL);

CREATE INDEX idx_iIsMind ON T_PRO_BULLETIN_AUDIT (I_IS_MIND);

CREATE INDEX idx_iRangeType ON T_PRO_BULLETIN_RANGE (I_RENGE_TYPE);

/*基础数据*/
--T_BULLETIN_TICKET_INFO
INSERT INTO T_BULLETIN_TICKET_INFO ( I_BULLETIN_SEG_ID, I_IS_SUP, I_TICKET_STATUS, I_BULLETIN_STATUS, I_KIND, I_RELATE_ID, S_RELATE_URL, S_CONTENT, I_RANGE, S_TITLE, S_CODE, I_LEVEL, D_BEGIN_DATE, D_END_DATE, I_NEED_FEEDBACK, I_APPOINT_DOMAIN, I_AUDIT_STAFF_ID, S_AUDIT_STAFF_NAME, I_DOMAIN_ID, S_DOMAIN_NAME, I_DEPT_ID, S_DEPT_NAME, I_STAFF_ID, S_STAFF_NAME, S_STAFF_TEL, D_CREATE_DATE, D_PIGEONHOLE_DATE, S_REMARK, I_ISSEND_OSS, I_FLAG_OSS, S_STAFF_ACCOUNT ) 
		 VALUES ( 558810, 1, 2, 5, 1, NULL, ' ', '待发布状态', 2, '待发布状态', 'CATT_NO1', 1, to_date('2011-09-27','YYYY-MM-DD'), to_date('2011-11-11','YYYY-MM-DD'), NULL, 2, NULL, ' ', 1030005, '省公司', 1500022542, '网管技术室', 1, '网络监控室测试', '18926239263', to_date('2011-09-27','YYYY-MM-DD'), to_date('2012-05-14','YYYY-MM-DD'), ' ', 0, 1, 'nocjktest' ); 

INSERT INTO T_BULLETIN_TICKET_INFO ( I_BULLETIN_SEG_ID, I_IS_SUP, I_TICKET_STATUS, I_BULLETIN_STATUS, I_KIND, I_RELATE_ID, S_RELATE_URL, S_CONTENT, I_RANGE, S_TITLE, S_CODE, I_LEVEL, D_BEGIN_DATE, D_END_DATE, I_NEED_FEEDBACK, I_APPOINT_DOMAIN, I_AUDIT_STAFF_ID, S_AUDIT_STAFF_NAME, I_DOMAIN_ID, S_DOMAIN_NAME, I_DEPT_ID, S_DEPT_NAME, I_STAFF_ID, S_STAFF_NAME, S_STAFF_TEL, D_CREATE_DATE, D_PIGEONHOLE_DATE, S_REMARK, I_ISSEND_OSS, I_FLAG_OSS, S_STAFF_ACCOUNT ) 
		 VALUES ( 558811, 1, 2, 5, 2, NULL, ' ', '待审核状态', 2, '待审核状态', 'CATT_NO2', 1, to_date('2011-09-27','YYYY-MM-DD'), to_date('2011-11-11','YYYY-MM-DD'), NULL, 2, 1100000621, '陈勃', 1030005, '省公司', 1500022542, '网管技术室', 1, '网络监控室测试', '18926239263', to_date('2011-09-27','YYYY-MM-DD'), to_date('2012-05-14','YYYY-MM-DD'), ' ', 0, 1, 'nocjktest' ); 

INSERT INTO T_BULLETIN_TICKET_INFO ( I_BULLETIN_SEG_ID, I_IS_SUP, I_TICKET_STATUS, I_BULLETIN_STATUS, I_KIND, I_RELATE_ID, S_RELATE_URL, S_CONTENT, I_RANGE, S_TITLE, S_CODE, I_LEVEL, D_BEGIN_DATE, D_END_DATE, I_NEED_FEEDBACK, I_APPOINT_DOMAIN, I_AUDIT_STAFF_ID, S_AUDIT_STAFF_NAME, I_DOMAIN_ID, S_DOMAIN_NAME, I_DEPT_ID, S_DEPT_NAME, I_STAFF_ID, S_STAFF_NAME, S_STAFF_TEL, D_CREATE_DATE, D_PIGEONHOLE_DATE, S_REMARK, I_ISSEND_OSS, I_FLAG_OSS, S_STAFF_ACCOUNT ) 
		 VALUES ( 558812, 1, 2, 5, 3, NULL, ' ', '待发布状态', 2, '待发布状态', 'CATT_NO3', 2, to_date('2011-09-27','YYYY-MM-DD'), to_date('2011-11-11','YYYY-MM-DD'), NULL, 2, NULL, ' ', 1030005, '省公司', 1500022542, '网管技术室', 1, '网络监控室测试', '18926239263', to_date('2011-09-27','YYYY-MM-DD'), to_date('2012-05-14','YYYY-MM-DD'), ' ', 0, 1, 'nocjktest' ); 

INSERT INTO T_BULLETIN_TICKET_INFO ( I_BULLETIN_SEG_ID, I_IS_SUP, I_TICKET_STATUS, I_BULLETIN_STATUS, I_KIND, I_RELATE_ID, S_RELATE_URL, S_CONTENT, I_RANGE, S_TITLE, S_CODE, I_LEVEL, D_BEGIN_DATE, D_END_DATE, I_NEED_FEEDBACK, I_APPOINT_DOMAIN, I_AUDIT_STAFF_ID, S_AUDIT_STAFF_NAME, I_DOMAIN_ID, S_DOMAIN_NAME, I_DEPT_ID, S_DEPT_NAME, I_STAFF_ID, S_STAFF_NAME, S_STAFF_TEL, D_CREATE_DATE, D_PIGEONHOLE_DATE, S_REMARK, I_ISSEND_OSS, I_FLAG_OSS, S_STAFF_ACCOUNT ) 
		 VALUES ( 10005134, 1, 1, 5, 5, NULL, ' ', '公告内容', 2, '公告标题5', 'CATT_NO8', 1, to_date('2011-09-27','YYYY-MM-DD'), to_date('2011-11-11','YYYY-MM-DD'), NULL, 2, NULL, ' ', 1030005, '省公司', 17, 'test', 1, '网络监控室测试', '18926239263', to_date('2011-09-27','YYYY-MM-DD'), NULL, ' ', 0, 0, 'nocjktest' ); 

INSERT INTO T_BULLETIN_TICKET_INFO ( I_BULLETIN_SEG_ID, I_IS_SUP, I_TICKET_STATUS, I_BULLETIN_STATUS, I_KIND, I_RELATE_ID, S_RELATE_URL, S_CONTENT, I_RANGE, S_TITLE, S_CODE, I_LEVEL, D_BEGIN_DATE, D_END_DATE, I_NEED_FEEDBACK, I_APPOINT_DOMAIN, I_AUDIT_STAFF_ID, S_AUDIT_STAFF_NAME, I_DOMAIN_ID, S_DOMAIN_NAME, I_DEPT_ID, S_DEPT_NAME, I_STAFF_ID, S_STAFF_NAME, S_STAFF_TEL, D_CREATE_DATE, D_PIGEONHOLE_DATE, S_REMARK, I_ISSEND_OSS, I_FLAG_OSS, S_STAFF_ACCOUNT ) 
		 VALUES ( 558854, 1, 2, 5, 3, NULL, ' ', '公告标题1', 2, '公告标题1', 'CATT_NO5', NULL, to_date('2011-09-27','YYYY-MM-DD'), to_date('2011-11-11','YYYY-MM-DD'), NULL, 2, NULL, ' ', 1030005, '省公司', 1500022542, '网管技术室', 1, '网络监控室测试', '18926239263', to_date('2011-09-27','YYYY-MM-DD'), to_date('2012-05-14','YYYY-MM-DD'), ' ', 0, 0, 'nocjktest' ); 

INSERT INTO T_BULLETIN_TICKET_INFO ( I_BULLETIN_SEG_ID, I_IS_SUP, I_TICKET_STATUS, I_BULLETIN_STATUS, I_KIND, I_RELATE_ID, S_RELATE_URL, S_CONTENT, I_RANGE, S_TITLE, S_CODE, I_LEVEL, D_BEGIN_DATE, D_END_DATE, I_NEED_FEEDBACK, I_APPOINT_DOMAIN, I_AUDIT_STAFF_ID, S_AUDIT_STAFF_NAME, I_DOMAIN_ID, S_DOMAIN_NAME, I_DEPT_ID, S_DEPT_NAME, I_STAFF_ID, S_STAFF_NAME, S_STAFF_TEL, D_CREATE_DATE, D_PIGEONHOLE_DATE, S_REMARK, I_ISSEND_OSS, I_FLAG_OSS, S_STAFF_ACCOUNT ) 
		 VALUES ( 558855, 1, 2, 5, 3, NULL, ' ', '公告标题2', 1, '公告标题2', 'CATT_NO6', 1, to_date('2011-09-27','YYYY-MM-DD'), to_date('2011-11-11','YYYY-MM-DD'), NULL, 2, NULL, ' ', 1030005, '省公司', 1500022542, '网管技术室', 1, '网络监控室测试', '18926239263', to_date('2011-09-27','YYYY-MM-DD'), to_date('2012-05-14','YYYY-MM-DD'), ' ', 0, 0, 'nocjktest' ); 

INSERT INTO T_BULLETIN_TICKET_INFO ( I_BULLETIN_SEG_ID, I_IS_SUP, I_TICKET_STATUS, I_BULLETIN_STATUS, I_KIND, I_RELATE_ID, S_RELATE_URL, S_CONTENT, I_RANGE, S_TITLE, S_CODE, I_LEVEL, D_BEGIN_DATE, D_END_DATE, I_NEED_FEEDBACK, I_APPOINT_DOMAIN, I_AUDIT_STAFF_ID, S_AUDIT_STAFF_NAME, I_DOMAIN_ID, S_DOMAIN_NAME, I_DEPT_ID, S_DEPT_NAME, I_STAFF_ID, S_STAFF_NAME, S_STAFF_TEL, D_CREATE_DATE, D_PIGEONHOLE_DATE, S_REMARK, I_ISSEND_OSS, I_FLAG_OSS, S_STAFF_ACCOUNT ) 
		 VALUES ( 558857, 1, 2, 5, 1, NULL, ' ', '公告标题3', 1, '公告标题3', 'CATT_NO7', 1, to_date('2011-09-27','YYYY-MM-DD'), to_date('2011-11-11','YYYY-MM-DD'), NULL, 2, NULL, ' ', 1030005, '省公司', 1500022542, '网管技术室', 1, '网络监控室测试', '18926239263', to_date('2011-09-27','YYYY-MM-DD'), to_date('2012-05-14','YYYY-MM-DD'), ' ', 0, 0, 'nocjktest' ); 

INSERT INTO T_BULLETIN_TICKET_INFO ( I_BULLETIN_SEG_ID, I_IS_SUP, I_TICKET_STATUS, I_BULLETIN_STATUS, I_KIND, I_RELATE_ID, S_RELATE_URL, S_CONTENT, I_RANGE, S_TITLE, S_CODE, I_LEVEL, D_BEGIN_DATE, D_END_DATE, I_NEED_FEEDBACK, I_APPOINT_DOMAIN, I_AUDIT_STAFF_ID, S_AUDIT_STAFF_NAME, I_DOMAIN_ID, S_DOMAIN_NAME, I_DEPT_ID, S_DEPT_NAME, I_STAFF_ID, S_STAFF_NAME, S_STAFF_TEL, D_CREATE_DATE, D_PIGEONHOLE_DATE, S_REMARK, I_ISSEND_OSS, I_FLAG_OSS, S_STAFF_ACCOUNT ) 
		 VALUES ( 10005135, 1, 1, 5, 3, NULL, ' ', '公告内容', 2, '公告标题5', 'CATT_NO9', 1, to_date('2011-09-27','YYYY-MM-DD'), to_date('2011-11-11','YYYY-MM-DD'), NULL, 2, NULL, ' ', 1030005, '省公司', 17, 'test', 1, '网络监控室测试', '18926239263', to_date('2011-09-27','YYYY-MM-DD'), NULL, ' ', 0, 0, 'nocjktest' ); 

INSERT INTO T_BULLETIN_TICKET_INFO ( I_BULLETIN_SEG_ID, I_IS_SUP, I_TICKET_STATUS, I_BULLETIN_STATUS, I_KIND, I_RELATE_ID, S_RELATE_URL, S_CONTENT, I_RANGE, S_TITLE, S_CODE, I_LEVEL, D_BEGIN_DATE, D_END_DATE, I_NEED_FEEDBACK, I_APPOINT_DOMAIN, I_AUDIT_STAFF_ID, S_AUDIT_STAFF_NAME, I_DOMAIN_ID, S_DOMAIN_NAME, I_DEPT_ID, S_DEPT_NAME, I_STAFF_ID, S_STAFF_NAME, S_STAFF_TEL, D_CREATE_DATE, D_PIGEONHOLE_DATE, S_REMARK, I_ISSEND_OSS, I_FLAG_OSS, S_STAFF_ACCOUNT ) 
		 VALUES ( 10005133, 1, 1, 5, 4, NULL, ' ', '公告内公告内容', 2, '公告标题6', 'CATT_NO10', 2, to_date('2011-09-27','YYYY-MM-DD'), to_date('2011-11-11','YYYY-MM-DD'), NULL, 2, NULL, ' ', 1030005, '省公司', 17, 'test', 1, '网络监控室测试', '18926239263', to_date('2011-09-27','YYYY-MM-DD'), NULL, ' ', 0, 0, 'nocjktest' ); 

INSERT INTO T_BULLETIN_TICKET_INFO ( I_BULLETIN_SEG_ID, I_IS_SUP, I_TICKET_STATUS, I_BULLETIN_STATUS, I_KIND, I_RELATE_ID, S_RELATE_URL, S_CONTENT, I_RANGE, S_TITLE, S_CODE, I_LEVEL, D_BEGIN_DATE, D_END_DATE, I_NEED_FEEDBACK, I_APPOINT_DOMAIN, I_AUDIT_STAFF_ID, S_AUDIT_STAFF_NAME, I_DOMAIN_ID, S_DOMAIN_NAME, I_DEPT_ID, S_DEPT_NAME, I_STAFF_ID, S_STAFF_NAME, S_STAFF_TEL, D_CREATE_DATE, D_PIGEONHOLE_DATE, S_REMARK, I_ISSEND_OSS, I_FLAG_OSS, S_STAFF_ACCOUNT ) 
		 VALUES ( 10005136, 1, 1, 5, 4, NULL, ' ', '公告内容', 2, '公告标题7', 'CATT_NO11', 2, to_date('2011-09-27','YYYY-MM-DD'), to_date('2011-11-11','YYYY-MM-DD'), NULL, 2, NULL, ' ', 1030005, '省公司', 17, 'test', 1, '网络监控室测试', '18926239263', to_date('2011-09-27','YYYY-MM-DD'), NULL, ' ', 0, 0, 'nocjktest' ); 


--T_PRO_BULLETIN_RANGE
INSERT INTO T_PRO_BULLETIN_RANGE ( I_RANGE_SEG_ID, I_BULLETIN_SEG_ID, I_RENGE_TYPE, I_OBJ_ID, S_OBJ_NAME, I_IS_TEMP_DATA, I_DOMAIN_ID, S_DOMAIN_NAME, I_RANGE_MARK, S_REMARK ) 
		 VALUES ( 10050832, 10050831, 3, 10001584, '罗德成测试', 2, 1030005, '省公司', 1, NULL ); 

INSERT INTO T_PRO_BULLETIN_RANGE ( I_RANGE_SEG_ID, I_BULLETIN_SEG_ID, I_RENGE_TYPE, I_OBJ_ID, S_OBJ_NAME, I_IS_TEMP_DATA, I_DOMAIN_ID, S_DOMAIN_NAME, I_RANGE_MARK, S_REMARK ) 
		 VALUES ( 10050833, 10050831, 3, 1500025057, '专业公司', 2, 1030005, '省公司', 1, NULL ); 

INSERT INTO T_PRO_BULLETIN_RANGE ( I_RANGE_SEG_ID, I_BULLETIN_SEG_ID, I_RENGE_TYPE, I_OBJ_ID, S_OBJ_NAME, I_IS_TEMP_DATA, I_DOMAIN_ID, S_DOMAIN_NAME, I_RANGE_MARK, S_REMARK ) 
		 VALUES ( 10055259, 10055256, 3, 10001584, '罗德成测试', 2, 1030005, '省公司', 1, NULL ); 

INSERT INTO T_PRO_BULLETIN_RANGE ( I_RANGE_SEG_ID, I_BULLETIN_SEG_ID, I_RENGE_TYPE, I_OBJ_ID, S_OBJ_NAME, I_IS_TEMP_DATA, I_DOMAIN_ID, S_DOMAIN_NAME, I_RANGE_MARK, S_REMARK ) 
		 VALUES ( 10055260, 10055256, 3, 1500025057, '专业公司', 2, 1030005, '省公司', 1, NULL );

INSERT INTO T_PRO_BULLETIN_RANGE ( I_RANGE_SEG_ID, I_BULLETIN_SEG_ID, I_RENGE_TYPE, I_OBJ_ID, S_OBJ_NAME, I_IS_TEMP_DATA, I_DOMAIN_ID, S_DOMAIN_NAME, I_RANGE_MARK, S_REMARK ) 
		 VALUES ( 10055261, 10055256, 3, 33412216, '其他', 2, 1010001, '深圳', 1, NULL ); 

INSERT INTO T_PRO_BULLETIN_RANGE ( I_RANGE_SEG_ID, I_BULLETIN_SEG_ID, I_RENGE_TYPE, I_OBJ_ID, S_OBJ_NAME, I_IS_TEMP_DATA, I_DOMAIN_ID, S_DOMAIN_NAME, I_RANGE_MARK, S_REMARK ) 
		 VALUES ( 10055262, 10055256, 3, 134553426, '深圳10000号亚运专席', 2, 1010001, '深圳', 1, NULL );
		 
--公告管理枚举数据
--I_BULLETIN_STATUS
INSERT INTO tbCtEnumTbl2 (sEnumTblName, sEnumColName, iEnumValue, sEnumName, isEnabled, sRemark, iDomainId) 
	VALUES('T_BULLETIN_TICKET_INFO', 'I_BULLETIN_STATUS', '1', '待审核', 1, NULL, 1);

INSERT INTO tbCtEnumTbl2 (sEnumTblName, sEnumColName, iEnumValue, sEnumName, isEnabled, sRemark, iDomainId) 
	VALUES('T_BULLETIN_TICKET_INFO', 'I_BULLETIN_STATUS', '2', '待修改', 1, NULL, 1);

INSERT INTO tbCtEnumTbl2 (sEnumTblName, sEnumColName, iEnumValue, sEnumName, isEnabled, sRemark, iDomainId) 
	VALUES('T_BULLETIN_TICKET_INFO', 'I_BULLETIN_STATUS', '3', '待发布', 1, NULL, 1);

INSERT INTO tbCtEnumTbl2 (sEnumTblName, sEnumColName, iEnumValue, sEnumName, isEnabled, sRemark, iDomainId) 
	VALUES('T_BULLETIN_TICKET_INFO', 'I_BULLETIN_STATUS', '4', '已发布', 1, NULL, 1);

INSERT INTO tbCtEnumTbl2 (sEnumTblName, sEnumColName, iEnumValue, sEnumName, isEnabled, sRemark, iDomainId) 
	VALUES('T_BULLETIN_TICKET_INFO', 'I_BULLETIN_STATUS', '5', '已结束', 1, NULL, 1);
	
--I_KIND
INSERT INTO tbCtEnumTbl2 (sEnumTblName, sEnumColName, iEnumValue, sEnumName, isEnabled, sRemark, iDomainId) 
	VALUES('T_BULLETIN_TICKET_INFO', 'I_KIND', '1', '故障公告', 1, NULL, 1);

INSERT INTO tbCtEnumTbl2 (sEnumTblName, sEnumColName, iEnumValue, sEnumName, isEnabled, sRemark, iDomainId) 
	VALUES('T_BULLETIN_TICKET_INFO', 'I_KIND', '2', '检修公告', 1, NULL, 1);

INSERT INTO tbCtEnumTbl2 (sEnumTblName, sEnumColName, iEnumValue, sEnumName, isEnabled, sRemark, iDomainId) 
	VALUES('T_BULLETIN_TICKET_INFO', 'I_KIND', '3', '事件公告', 1, NULL, 1);

INSERT INTO tbCtEnumTbl2 (sEnumTblName, sEnumColName, iEnumValue, sEnumName, isEnabled, sRemark, iDomainId) 
	VALUES('T_BULLETIN_TICKET_INFO', 'I_KIND', '4', '新闻公告', 1, NULL, 1);

INSERT INTO tbCtEnumTbl2 (sEnumTblName, sEnumColName, iEnumValue, sEnumName, isEnabled, sRemark, iDomainId) 
	VALUES('T_BULLETIN_TICKET_INFO', 'I_KIND', '5', '预警公告', 1, NULL, 1);

INSERT INTO tbCtEnumTbl2 (sEnumTblName, sEnumColName, iEnumValue, sEnumName, isEnabled, sRemark, iDomainId) 
	VALUES('T_BULLETIN_TICKET_INFO', 'I_KIND', '6', '管理公告', 1, NULL, 1);

INSERT INTO tbCtEnumTbl2 (sEnumTblName, sEnumColName, iEnumValue, sEnumName, isEnabled, sRemark, iDomainId) 
	VALUES('T_BULLETIN_TICKET_INFO', 'I_KIND', '7', '其他公告', 1, NULL, 1);
	
--I_LEVEL
INSERT INTO tbCtEnumTbl2 (sEnumTblName, sEnumColName, iEnumValue, sEnumName, isEnabled, sRemark, iDomainId) 
	VALUES('T_BULLETIN_TICKET_INFO', 'I_LEVEL', '1', '重要', 1, NULL, 1);

INSERT INTO tbCtEnumTbl2 (sEnumTblName, sEnumColName, iEnumValue, sEnumName, isEnabled, sRemark, iDomainId) 
	VALUES('T_BULLETIN_TICKET_INFO', 'I_LEVEL', '2', '普通', 1, NULL, 1);

--I_RANGE
INSERT INTO tbCtEnumTbl2 (sEnumTblName, sEnumColName, iEnumValue, sEnumName, isEnabled, sRemark, iDomainId) 
	VALUES('T_BULLETIN_TICKET_INFO', 'I_RANGE', '1', '全省范围', 1, NULL, 1);

INSERT INTO tbCtEnumTbl2 (sEnumTblName, sEnumColName, iEnumValue, sEnumName, isEnabled, sRemark, iDomainId) 
	VALUES('T_BULLETIN_TICKET_INFO', 'I_RANGE', '2', '公司内部', 1, NULL, 1);

INSERT INTO tbCtEnumTbl2 (sEnumTblName, sEnumColName, iEnumValue, sEnumName, isEnabled, sRemark, iDomainId) 
	VALUES('T_BULLETIN_TICKET_INFO', 'I_RANGE', '3', '部门内部', 1, NULL, 1);
	
INSERT INTO tbCtEnumTbl2 (sEnumTblName, sEnumColName, iEnumValue, sEnumName, isEnabled, sRemark, iDomainId) 
	VALUES('T_BULLETIN_TICKET_INFO', 'I_RANGE', '4', '其他', 1, NULL, 1);

--I_IS_MIND
INSERT INTO tbCtEnumTbl2 (sEnumTblName, sEnumColName, iEnumValue, sEnumName, isEnabled, sRemark, iDomainId) 
	VALUES('T_PRO_BULLETIN_AUDIT', 'I_IS_MIND', '1', '通过', 1, NULL, 1);

INSERT INTO tbCtEnumTbl2 (sEnumTblName, sEnumColName, iEnumValue, sEnumName, isEnabled, sRemark, iDomainId) 
	VALUES('T_PRO_BULLETIN_AUDIT', 'I_IS_MIND', '2', '回退', 1, NULL, 1);

INSERT INTO tbCtEnumTbl2 (sEnumTblName, sEnumColName, iEnumValue, sEnumName, isEnabled, sRemark, iDomainId) 
	VALUES('T_PRO_BULLETIN_AUDIT', 'I_IS_MIND', '3', '撤销', 1, NULL, 1);
